# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: ccfd5be94f8096b57f4a27ac07e03227913cf3f2d935159daf472a19ba2f472538f5188fb50f5e9a07ab085f4aa17c0c2211442b502b34cf3c4362f6db319646

test:
  secret_key_base: 1dc03ed1ce66fca22c8292d08c61dfd328819e591fdff4335b2efd60f7455c097067579ac599c6db21e0b97d21cc01fbb62c45f180ec1b71e43e481850545f3a

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
